#include "mainwindow.h"
#include "DashboardWidget.h"
#include "RoomPageWidget.h"
#include "ReservationsPageWidget.h"
#include "RoomStatusPageWidget.h"
#include "ui_mainwindow.h"
#include <QStyle>
#include <QTimer>
#include <QDateTime>

MainWindow::MainWindow(HotelManager* manager, QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
    , m_manager(manager)
{
    ui->setupUi(this);
    this->setFixedSize(1280, 720);
    this->setWindowTitle("Hệ Thống Quản Lý Khách Sạn");

    // Clear default empty pages generated by Qt Designer
    while (ui->stackedWidget->count() > 0) {
        QWidget* w = ui->stackedWidget->widget(0);
        ui->stackedWidget->removeWidget(w);
        delete w;
    }

    // Create the page widgets
    m_dashboardPage = new DashboardWidget(m_manager, this);
    m_dashboardPage->setObjectName("pageDashboard");

    m_reservationsPage = new ReservationsPageWidget(m_manager, this);
    m_reservationsPage->setObjectName("pageReservations");

    m_roomPage = new RoomPageWidget(m_manager, this);
    m_roomPage->setObjectName("pageRoom");

    m_roomStatusPage = new RoomStatusPageWidget(m_manager, this);
    m_roomStatusPage->setObjectName("pageRoomStatus");

    // Add widgets to stackedWidget
    ui->stackedWidget->addWidget(m_dashboardPage);      // Index 0
    ui->stackedWidget->addWidget(m_reservationsPage);  // Index 1
    ui->stackedWidget->addWidget(m_roomPage);          // Index 2
    ui->stackedWidget->addWidget(m_roomStatusPage);      // Index 3

    // Configure sidebar buttons to be checkable & exclusive (acting as tabs)
    QList<QPushButton*> buttons = { ui->btnDashboard, ui->btnReservation, ui->btnRoom, ui->btnRoomStatus };
    for (QPushButton* btn : buttons) {
        btn->setCheckable(true);
        btn->setAutoExclusive(true);
    }

    // Connect navigation signals
    connect(ui->btnDashboard, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(0);
            updateButtonStyle(ui->btnDashboard);
            m_dashboardPage->refreshDashboard();
        }
    });

    connect(ui->btnReservation, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(1);
            updateButtonStyle(ui->btnReservation);
            m_reservationsPage->refreshData();
        }
    });

    connect(ui->btnRoom, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(2);
            updateButtonStyle(ui->btnRoom);
            m_roomPage->refreshData();
        }
    });

    connect(ui->btnRoomStatus, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(3);
            updateButtonStyle(ui->btnRoomStatus);
            m_roomStatusPage->refreshData();
        }
    });

    // Default to Dashboard checked & displayed
    ui->btnDashboard->setChecked(true);
    ui->stackedWidget->setCurrentWidget(m_dashboardPage);
    updateButtonStyle(ui->btnDashboard);
}

void MainWindow::updateButtonStyle(QPushButton* activeBtn) {
    QList<QPushButton*> buttons = { ui->btnDashboard, ui->btnReservation, ui->btnRoom, ui->btnRoomStatus };

    for (QPushButton* btn : buttons) {
        bool isActive = (btn == activeBtn);
        btn->setProperty("active", isActive);
        btn->style()->unpolish(btn);
        btn->style()->polish(btn);
    }
}

MainWindow::~MainWindow()
{
    delete ui;
}
