#include "mainwindow.h"
#include "DashboardWidget.h"
#include "RoomPageWidget.h"
#include "ReservationsPageWidget.h"
#include "CustomerPageWidget.h"
#include "RoomStatusPageWidget.h"
#include "StatisticsPageWidget.h"
#include "ui_mainwindow.h"
#include <QApplication>
#include <QStyle>
#include <QTimer>
#include <QDateTime>
#include <QButtonGroup>
#include <QHBoxLayout>
#include <QStackedWidget>
#include <QVBoxLayout>
#include <QPainter>
#include <QSvgRenderer>
namespace {

QIcon createTintedIcon(const QString& svgPath, const QColor& color) {
    QPixmap pixmap(24, 24);
    pixmap.fill(Qt::transparent);
    QPainter painter(&pixmap);
    QSvgRenderer renderer(svgPath);
    renderer.render(&painter);
    painter.setCompositionMode(QPainter::CompositionMode_SourceIn);
    painter.fillRect(pixmap.rect(), color);
    painter.end();
    return QIcon(pixmap);
}

// Modified: Apply one unobtrusive scrollbar and focus treatment across pages so tables, lists, and combo popups feel consistent.
void applyGlobalPresentationStyle()
{
    qApp->setStyleSheet(R"(
        QAbstractScrollArea { background: transparent; }
        QAbstractScrollArea::corner { background: transparent; }
        QAbstractScrollArea::viewport { background: transparent; }
        QScrollBar:vertical {
            background: transparent;
            width: 10px;
            margin: 4px 2px 4px 2px;
        }
        QScrollBar::handle:vertical {
            background: #C7D4E7;
            border-radius: 5px;
            min-height: 42px;
        }
        QScrollBar::handle:vertical:hover { background: #8FB0E8; }
        QScrollBar::handle:vertical:pressed { background: #5F8FE0; }
        QScrollBar:horizontal {
            background: transparent;
            height: 10px;
            margin: 2px 4px 2px 4px;
        }
        QScrollBar::handle:horizontal {
            background: #C7D4E7;
            border-radius: 5px;
            min-width: 42px;
        }
        QScrollBar::handle:horizontal:hover { background: #8FB0E8; }
        QScrollBar::handle:horizontal:pressed { background: #5F8FE0; }
        QScrollBar::add-line, QScrollBar::sub-line { width: 0; height: 0; }
        QScrollBar::add-page, QScrollBar::sub-page { background: transparent; }
        QComboBox QAbstractItemView {
            background: #FFFFFF;
            color: #2B3674;
            border: 1px solid #DCE6F5;
            border-radius: 8px;
            outline: none;
            padding: 4px;
        }
        QComboBox QAbstractItemView::item {
            min-height: 28px;
            padding: 4px 8px;
        }
        QComboBox QAbstractItemView::item:selected {
            background: #EAF2FF;
            color: #3B58FF;
            border-radius: 5px;
        }
        QLineEdit:focus, QComboBox:focus, QDateTimeEdit:focus, QSpinBox:focus {
            border-color: #3B58FF;
        }
        QLineEdit:disabled, QComboBox:disabled, QDateTimeEdit:disabled, QSpinBox:disabled {
            color: #8FA0BD;
            background: #F4F7FE;
        }
        QToolTip {
            background: #FFFFFF;
            color: #2B3674;
            border: 1px solid #DCE6F5;
            border-radius: 7px;
            padding: 6px 9px;
        }
    )");
}
}

MainWindow::MainWindow(HotelManager* manager, QWidget *parent)
    : QMainWindow(parent)
    , ui(new Ui::MainWindow)
    , m_manager(manager)
{
    ui->setupUi(this);
    applyGlobalPresentationStyle();
    this->setMinimumSize(1180, 700);
    const QRect availableScreen = QGuiApplication::primaryScreen()->availableGeometry();
    const int restoredWidth = qBound(1180, availableScreen.width() - 48, 1360);
    // Modified: Give the restored application window enough horizontal room for full reservation actions without disturbing page layouts.
    this->resize(restoredWidth, 720);
    this->setWindowTitle("Hotel Management System");

    // Clear default empty pages generated by Qt Designer
    while (ui->stackedWidget->count() > 0) {
        QWidget* w = ui->stackedWidget->widget(0);
        ui->stackedWidget->removeWidget(w);
        delete w;
    }

    // Create the page widgets
    m_dashboardPage = new DashboardWidget(m_manager, this);
    m_dashboardPage->setObjectName("pageDashboard");

    m_reservationsPage = new ReservationsPageWidget(m_manager, this);
    m_reservationsPage->setObjectName("pageReservations");

    // Modified and optimized performance: refresh history immediately after a persisted checkout.
    connect(m_reservationsPage, &ReservationsPageWidget::bookingCompleted,
            m_dashboardPage, &DashboardWidget::refreshDashboard);

    m_customerPage = new CustomerPageWidget(m_manager, this);
    m_customerPage->setObjectName("pageCustomer");

    m_roomPage = new RoomPageWidget(m_manager, this);
    m_roomPage->setObjectName("pageRoom");

    m_roomStatusPage = new RoomStatusPageWidget(m_manager, this);
    m_roomStatusPage->setObjectName("pageRoomStatus");

    // Reservation is one destination with Room Status and Reservation Details subpages.
    m_reservationContainer = new QWidget(this);
    m_reservationContainer->setObjectName("pageReservationContainer");
    auto* reservationContainerLayout = new QVBoxLayout(m_reservationContainer);
    reservationContainerLayout->setContentsMargins(0, 0, 0, 0);
    reservationContainerLayout->setSpacing(0);

    auto* reservationTabs = new QWidget(m_reservationContainer);
    reservationTabs->setObjectName("reservationBookmarkBar");
    auto* reservationTabsLayout = new QHBoxLayout(reservationTabs);
    reservationTabsLayout->setContentsMargins(22, 10, 22, 0);
    reservationTabsLayout->setSpacing(6);
    m_roomStatusTab = new QPushButton("Room Status", reservationTabs);
    m_reservationDetailsTab = new QPushButton("Reservation Details", reservationTabs);
    for (QPushButton* tab : {m_roomStatusTab, m_reservationDetailsTab}) {
        tab->setCheckable(true);
        tab->setMinimumWidth(180);
        tab->setMinimumHeight(42);
        tab->setProperty("reservationBookmark", true);
        reservationTabsLayout->addWidget(tab);
    }
    reservationTabsLayout->addStretch();
    auto* reservationTabGroup = new QButtonGroup(m_reservationContainer);
    reservationTabGroup->setExclusive(true);
    reservationTabGroup->addButton(m_roomStatusTab, 0);
    reservationTabGroup->addButton(m_reservationDetailsTab, 1);

    m_reservationSubPages = new QStackedWidget(m_reservationContainer);
    m_reservationSubPages->setObjectName("reservationSubPages");
    m_reservationSubPages->addWidget(m_roomStatusPage);
    m_reservationSubPages->addWidget(m_reservationsPage);
    reservationContainerLayout->addWidget(reservationTabs);
    reservationContainerLayout->addWidget(m_reservationSubPages, 1);
    m_reservationContainer->setStyleSheet(R"(
        QWidget#reservationBookmarkBar { background: transparent; border-bottom: 1px solid #D7E3F4; }
        QPushButton[reservationBookmark="true"] {
            background: #E8EEF8; color: #66789B; border: 1px solid #D7E3F4;
            border-bottom: none; border-top-left-radius: 12px; border-top-right-radius: 12px;
            padding: 10px 22px; font-size: 14px; font-weight: 700;
        }
        QPushButton[reservationBookmark="true"]:hover { background: #EFF6FF; color: #1D4ED8; }
        QPushButton[reservationBookmark="true"]:checked {
            background: #FFFFFF; color: #005BFE; border-color: #93C5FD;
            padding-top: 8px; border-top: 3px solid #005BFE;
        }
    )");
    connect(reservationTabGroup, &QButtonGroup::idClicked,
            this, &MainWindow::showReservationSubPage);
    showReservationSubPage(0);

    m_statisticsPage = new StatisticsPageWidget(m_manager, this);
    m_statisticsPage->setObjectName("pageStatistics");

    connect(m_reservationsPage, &ReservationsPageWidget::bookingCompleted,
            m_roomStatusPage, &RoomStatusPageWidget::refreshData);

    connect(m_reservationsPage, &ReservationsPageWidget::bookingCompleted,
            m_statisticsPage, &StatisticsPageWidget::refreshData);

    // Keep Room Status visible behind the combined room-review/reservation modal.
    connect(m_roomStatusPage, &RoomStatusPageWidget::bookingRequested,
            this, [this](const QString& roomNumber, const QDateTime& checkIn, const QDateTime& checkOut,
                         int adults, int children) {
                m_reservationsPage->refreshData();
                m_reservationsPage->startNewReservationForRoom(roomNumber, checkIn, checkOut, adults, children);
            });

    connect(m_reservationsPage, &ReservationsPageWidget::bookingChanged,
            this, [this]() {
                m_roomStatusPage->refreshData();
                m_dashboardPage->refreshDashboard();
                m_statisticsPage->refreshData();
            });

    connect(m_dashboardPage, &DashboardWidget::reservationActionRequested,
            this, [this](const QString& bookingId, const QString& actionType) {
                m_reservationsPage->performBookingAction(bookingId, actionType);
            });

    connect(m_reservationsPage, &ReservationsPageWidget::roomStatusBookingCancelled,
            this, [this]() {
                ui->stackedWidget->setCurrentWidget(m_reservationContainer);
                ui->btnReservation->setChecked(true);
                updateButtonStyle(ui->btnReservation);
                showReservationSubPage(0);
                m_roomStatusPage->refreshData();
            });

    // Add widgets to stackedWidget
    ui->stackedWidget->addWidget(m_dashboardPage);      // Index 0
    ui->stackedWidget->addWidget(m_reservationContainer); // Index 1
    ui->stackedWidget->addWidget(m_customerPage);      // Index 2
    ui->stackedWidget->addWidget(m_roomPage);          // Index 3
    ui->stackedWidget->addWidget(m_statisticsPage);    // Index 4

    // Configure sidebar buttons to be checkable & exclusive (acting as tabs)
    ui->btnRoomStatus->hide();
    QList<QPushButton*> buttons = { ui->btnDashboard, ui->btnReservation, ui->btnCustomer, ui->btnRoom, ui->btnStatistics };
    for (QPushButton* btn : buttons) {
        btn->setCheckable(true);
        btn->setAutoExclusive(true);
    }

    // Connect navigation signals
    connect(ui->btnDashboard, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(0);
            updateButtonStyle(ui->btnDashboard);
            m_dashboardPage->refreshDashboard();
        }
    });

    connect(ui->btnReservation, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(1);
            updateButtonStyle(ui->btnReservation);
            if (m_reservationSubPages->currentIndex() == 0) m_roomStatusPage->refreshData();
            else m_reservationsPage->refreshData();
        }
    });

    connect(ui->btnCustomer, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(2);
            updateButtonStyle(ui->btnCustomer);
            m_customerPage->refreshData();
        }
    });

    connect(ui->btnRoom, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(3);
            updateButtonStyle(ui->btnRoom);
            m_roomPage->refreshData();
        }
    });

    connect(ui->btnStatistics, &QPushButton::toggled, this, [=](bool checked) {
        if (checked) {
            ui->stackedWidget->setCurrentIndex(4);
            updateButtonStyle(ui->btnStatistics);
            m_statisticsPage->refreshData();
        }
    });

    // Default to Dashboard checked & displayed
    ui->btnDashboard->setChecked(true);
    ui->stackedWidget->setCurrentWidget(m_dashboardPage);
    updateButtonStyle(ui->btnDashboard);
}

void MainWindow::updateButtonStyle(QPushButton* activeBtn) {
    QList<QPushButton*> buttons = { ui->btnDashboard, ui->btnReservation, ui->btnCustomer, ui->btnRoom, ui->btnRoomStatus, ui->btnStatistics };
    
    QMap<QPushButton*, QString> buttonIcons = {
        {ui->btnDashboard, ":/ic_dashboard.svg"},
        {ui->btnReservation, ":/ic_reservation.svg"},
        {ui->btnCustomer, ":/ic_customer.svg"},
        {ui->btnRoom, ":/ic_room.svg"},
        {ui->btnRoomStatus, ":/ic_room_status.svg"},
        {ui->btnStatistics, ":/ic_statistics.svg"}
    };

    for (QPushButton* btn : buttons) {
        bool isActive = (btn == activeBtn);
        btn->setProperty("active", isActive);
        btn->style()->unpolish(btn);
        btn->style()->polish(btn);
        
        QColor iconColor = isActive ? QColor("#3B58FF") : QColor("#2B3674");
        btn->setIcon(createTintedIcon(buttonIcons[btn], iconColor));
    }
}

void MainWindow::showReservationSubPage(int index)
{
    if (!m_reservationSubPages) return;
    const int boundedIndex = index == 1 ? 1 : 0;
    m_reservationSubPages->setCurrentIndex(boundedIndex);
    m_roomStatusTab->setChecked(boundedIndex == 0);
    m_reservationDetailsTab->setChecked(boundedIndex == 1);
    if (boundedIndex == 0) m_roomStatusPage->refreshData();
    else m_reservationsPage->refreshData();
}

void MainWindow::showReservationSubPage(int index)
{
    if (!m_reservationSubPages) return;
    const int boundedIndex = index == 1 ? 1 : 0;
    m_reservationSubPages->setCurrentIndex(boundedIndex);
    m_roomStatusTab->setChecked(boundedIndex == 0);
    m_reservationDetailsTab->setChecked(boundedIndex == 1);
    if (boundedIndex == 0) m_roomStatusPage->refreshData();
    else m_reservationsPage->refreshData();
}

MainWindow::~MainWindow()
{
    delete ui;
}
